version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - spring-cloud-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - spring-cloud-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 19000:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./kafka-ui/dynamic_config.yaml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - spring-cloud-network
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    networks:
      - spring-cloud-network
    ports:
      - "1521:1521"
    volumes:
      - ./startup-scripts/:/opt/oracle/scripts/startup
    environment:
      ORACLE_PWD: pass!123
version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - spring-cloud-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - spring-cloud-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 19000:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./kafka-ui/dynamic_config.yaml:/etc/kafkaui/dynamic_config.yaml
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    ports:
      - "1521:1521"
    volumes:
      - ./startup-scripts/:/opt/oracle/scripts/startup
    environment:
      ORACLE_PWD: pass!123
    networks:
        - spring-cloud-network
  api-consumer:
    container_name: api-consumer
    build:
        context: consumer
        dockerfile: Dockerfile
    image: api-consumer:latest
    ports:
      - 8080:8080
    environment:
          - DB_HOST=oracle-db
          - DB_PORT=1521
          - DB_DATABASE=xe
          - DB_USER=consumer
          - DB_PASSWORD=pass54321
          - SERVER_PORT=8080
          - KAFKA_HOST=kafka
          - KAFKA_PORT=9092
    networks:
        - spring-cloud-network
    depends_on:
      oracle-db:
        condition: service_healthy
volumes:
  postgres-data:
networks:
    spring-cloud-network:
        driver: bridge
